# Generated by Django 4.2.16 on 2024-12-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription",
            field=models.BooleanField(
                default=False, null=True, verbose_name="有料会員"
            ),
        ),
    ]
