# Generated by Django 4.2.16 on 2025-01-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="card_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="カード名義"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="card_number",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="カード番号"
            ),
        ),
    ]
