# Generated by Django 4.2.16 on 2024-10-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "カテゴリー一覧",
                "verbose_name_plural": "テゴリー一覧",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "お気に入り一覧",
                "verbose_name_plural": "お気に入り一覧",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "予約一覧", "verbose_name_plural": "予約一覧"},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"verbose_name": "店舗一覧", "verbose_name_plural": "店舗一覧"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "verbose_name": "レビュー一覧",
                "verbose_name_plural": "レビュー一覧",
            },
        ),
    ]
